base_driver:
  ros__parameters:
    port: "/dev/esp32"   # symlink estable (regla udev 99-esp32.rules)
    baud: 115200
    wheel_radius: 0.035
    base_width: 0.145
    ticks_per_revolution: 4532
    cmd_vel_timeout: 0.25
    serial_rx_timeout: 0.25
    verbose_serial: false
