amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: /scan
    min_particles: 500
    max_particles: 2000

map_server:
  ros__parameters:
    use_sim_time: false

bt_navigator:
  ros__parameters:
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.25
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      regulate_max_speed: true
      transform_tolerance: 0.2

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.125
      use_astar: true
      allow_unknown: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      resolution: 0.05
      update_frequency: 10.0
      publish_frequency: 5.0
      rolling_window: true
      width: 6.0
      height: 6.0
      footprint: "[[0.2,0.15], [0.2,-0.15], [-0.2,-0.15], [-0.2,0.15]]"
      plugins: ["obstacle_layer","inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: lidar
        lidar:
          topic: /scan
          data_type: LaserScan
          clearing: true
          marking: true
          max_obstacle_height: 0.40
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05
      publish_frequency: 2.0
      update_frequency: 2.0
      rolling_window: false
      width: 20.0
      height: 20.0
      footprint: "[[0.2,0.15], [0.2,-0.15], [-0.2,-0.15], [-0.2,0.15]]"
      plugins: ["obstacle_layer","inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: lidar
        lidar:
          topic: /scan
          data_type: LaserScan
          clearing: true
          marking: true
          max_obstacle_height: 0.40
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.8

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: [
      "controller_server",
      "planner_server",
      "behavior_server",
      "bt_navigator",
      "waypoint_follower",
      "map_server",
      "amcl"
    ]
